USE [Database]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[fnCalculateBusinessDays.sql] (@StartDate datetime, @EndDate datetime)

RETURNS INT

AS
BEGIN

    DECLARE @NUMBUSDAYS AS INT
    DECLARE @NUMTOTALDAYS AS INT

    SET @NUMBUSDAYS=0
    SET @NUMTOTALDAYS=DATEDIFF(DD,@STARTDATE,@ENDDATE)

    WHILE @NUMTOTALDAYS>=0

    BEGIN
        IF (DATEPART(DW,DATEADD(D,@NUMTOTALDAYS,@STARTDATE)) >1 AND DATEPART(DW,DATEADD(D,@NUMTOTALDAYS,@STARTDATE))<7)
            BEGIN 
                SET @NUMBUSDAYS=@NUMBUSDAYS+1
            END

        SET @NUMTOTALDAYS=@NUMTOTALDAYS-1
    END

    RETURN @NUMBUSDAYS

END 
